export const MAINTRACKS = [
  {
    idTrack: 1,
    name: 'Guilt',
    addition: '',
    author: 'Nero',
    album: 'Welcome Reality',
    time: '4:44',
  },

  {
    idTrack: 2,
    name: 'Elektro',
    addition: '',
    author: 'Dynoro, Outwork, Mr. Gee',
    album: 'Elektro',
    time: '2:22',
  },

  {
    idTrack: 3,
    name: 'I’m Fire',
    addition: '',
    author: 'Ali Bakgor',
    album: 'I’m Fire',
    time: '2:22',
  },
  {
    idTrack: 4,
    name: 'Non Stop',
    addition: '(Remix)',
    author: 'Стоункат, Psychopath',
    album: 'Non Stop',
    time: '4:12',
  },
  {
    idTrack: 5,
    name: 'Run Run',
    addition: '(feat. AR/CO)',
    author: 'Jaded, Will Clarke, AR/CO',
    album: 'Run Run',
    time: '2:54',
  },
  {
    idTrack: 6,
    name: 'Eyes on Fire',
    addition: '(Zeds Dead Remix)',
    author: 'Blue Foundation, Zeds Dead',
    album: 'Eyes on Fire',
    time: '5:20',
  },
  {
    idTrack: 7,
    name: 'Mucho Bien',
    addition: '(Hi Profile Remix)',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    album: 'Mucho Bien',
    time: '3:41',
  },
  {
    idTrack: 8,
    name: 'Knives n Cherries',
    addition: '',
    author: 'minthaze',
    album: 'Captivating',
    time: '1:48',
  },
  {
    idTrack: 9,
    name: 'How Deep Is Your Love',
    addition: '',
    author: 'Calvin Harris, Disciples',
    album: 'How Deep Is Your Love',
    time: '3:32',
  },
  {
    idTrack: 10,
    name: 'Morena',
    addition: '',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    time: '3:36',
  },
]
