import playlist01 from '../img/playlist01.png'
import playlist02 from '../img/playlist02.png'
import playlist03 from '../img/playlist03.png'

export const PLAYLISTS = [
  {
    id: 1,
    img: playlist01,
    title: 'Плейлист дня',
    tracks: [
      {
        idTrack: 1,
        name: 'Fdfdf',
        addition: '',
        author: 'Taylor Swift',
        album: 'dfdf',
        time: '2:44',
      },
      {
        idTrack: 2,
        name: 'ffddsf',
        addition: '',
        album: 'dfjghjhdf',
        author: 'Tadfsdfdf',
        time: '2:34',
      },
      {
        idTrack: 3,
        name: 'aggjghj',
        addition: '',
        album: 'nbvnvbn',
        author: 'kjjlkjl',
        time: '5:44',
      },
      {
        idTrack: 4,
        name: 'lklklk',
        addition: '',
        album: 'cxxczxc',
        author: 'plc;lmldklk',
        time: '2:21',
      },
      {
        idTrack: 5,
        name: 'guioioiuo',
        addition: '',
        album: 'vbnmmn',
        author: 'fgfghfghg',
        time: '4:44',
      },
    ],
  },
  {
    id: 2,
    img: playlist02,
    title: '100 танцевальных хитов',
    tracks: [
      {
        idTrack: 1,
        name: 'sdasdd',
        addition: '',
        album: 'xvcvcv',
        author: 'Swift',
        time: '2:44',
      },
      {
        idTrack: 2,
        name: 'jjhgjh',
        addition: '',
        album: 'iuyuiyuiu',
        author: 'fhfthf',
        time: '2:34',
      },
      {
        idTrack: 3,
        name: 'ghjghjghj',
        addition: '',
        album: 'fdhftyjhj',
        author: 'oiuouio',
        time: '5:44',
      },
      {
        idTrack: 4,
        name: 'qwqqw',
        addition: '',
        album: 'oioioi',
        author: 'plc',
        time: '2:21',
      },
      {
        idTrack: 5,
        name: 'fgfgtrrrr',
        addition: 'dsdfd',
        album: 'asaaa',
        author: 'zxcvvbvb',
        time: '4:44',
      },
    ],
  },
  {
    id: 3,
    img: playlist03,
    title: 'Инди заряд',
    tracks: [
      {
        idTrack: 1,
        name: 'zczxcxc',
        addition: '',
        album: ' cdcdc',
        author: 'sdfsdfdsf',
        time: '2:44',
      },
      {
        idTrack: 2,
        name: 'aaaaaa',
        addition: 'sdfdf',
        album: 'ghghgh',
        author: 'iioioui',
        time: '2:34',
      },
      {
        idTrack: 3,
        name: 'ggggg',
        addition: '',
        album: 'vvvvv',
        author: 'vccddd',
        time: '5:44',
      },
      {
        idTrack: 4,
        name: 'iouioo',
        addition: '',
        album: 'ererettyy',
        author: 'ddsfsf',
        time: '2:21',
      },
      {
        idTrack: 5,
        name: 'dfdsfdsfdf',
        addition: '',
        album: 'bvbnbnmn',
        author: 'qwqqqq',
        time: '4:44',
      },
    ],
  },
]
